import test from 'node:test';
import assert from 'node:assert/strict';
import { DOMParser } from '@xmldom/xmldom';

import { generateFatturaXML, type FatturaXMLData } from './generator';
import { righeFromXml } from './righeFromXml';

const parse = (xml: string) => new DOMParser().parseFromString(xml, 'text/xml') as unknown as Document;
const base: FatturaXMLData = {
  emittente: { codiceFiscale: 'RSSMRA80A01H501U', nome: 'Mario', cognome: 'Rossi', indirizzo: 'Via', numeroCivico: '1', cap: '00100', comune: 'Roma', provincia: 'RM', nazione: 'IT' },
  partitaIva: '01234567890', cliente: { denominazione: 'Acme', nazione: 'IT' }, numero: '07', data: '2026-03-10',
  righe: [{ descrizione: 'Sviluppo', quantita: 2, prezzoUnitario: 500 }, { descrizione: 'Nota', quantita: 1, prezzoUnitario: 0 }],
};

test('an EUR invoice generated by the app round-trips', () => {
  assert.deepEqual(righeFromXml(parse(generateFatturaXML(base))), { ok: true, righe: base.righe, valuta: 'EUR' });
});

test('a foreign-currency invoice round-trips in the original currency and regenerates the same EUR amounts', () => {
  const data: FatturaXMLData = { ...base, righe: [{ descrizione: 'Workshop', quantita: 3, prezzoUnitario: 333.33 }, { descrizione: 'Viaggio', quantita: 1, prezzoUnitario: 120 }], valuta: 'GBP', tassoCambio: 0.8412, dataCambio: '2026-03-09' };
  const xml1 = generateFatturaXML(data);
  const out = righeFromXml(parse(xml1));
  assert.equal(out.ok, true);
  if (!out.ok) return;
  assert.equal(out.valuta, 'GBP');
  assert.equal(out.tassoCambio, 0.8412);
  assert.equal(out.dataCambio, '2026-03-09');
  assert.equal(out.importoValuta, 1119.99);
  assert.deepEqual(out.righe.map((r) => [r.descrizione, r.quantita, Math.round(r.prezzoUnitario * 100) / 100]), [['Workshop', 3, 333.33], ['Viaggio', 1, 120]]);
  const xml2 = generateFatturaXML({ ...data, righe: out.righe, tassoCambio: out.tassoCambio, dataCambio: out.dataCambio });
  const amounts = (x: string) => [...x.matchAll(/<(PrezzoTotale|ImponibileImporto|ImportoTotaleDocumento)>([^<]+)</g)].map((m) => m[2]);
  assert.deepEqual(amounts(xml2), amounts(xml1));
});

const replace = (xml: string, from: RegExp, to: string) => { const out = xml.replace(from, to); assert.notEqual(out, xml, `pattern ${from} not found`); return out; };

test('non-representable invoices are rejected with a reason', () => {
  const xml = generateFatturaXML({ ...base, righe: [{ descrizione: 'Sviluppo', quantita: 1, prezzoUnitario: 100 }] });
  const cases: Array<[string, string]> = [
    ['iva', replace(xml, /<AliquotaIVA>0\.00<\/AliquotaIVA>/, '<AliquotaIVA>22.00</AliquotaIVA>')],
    ['sconto', replace(xml, /<PrezzoTotale>/, '<ScontoMaggiorazione><Tipo>SC</Tipo><Importo>10</Importo></ScontoMaggiorazione><PrezzoTotale>')],
    ['totale riga', replace(xml, /<PrezzoTotale>100\.00<\/PrezzoTotale>/, '<PrezzoTotale>90.00</PrezzoTotale>')],
    ['riepilogo', replace(xml, /<ImponibileImporto>100\.00</, '<ImponibileImporto>120.00<')],
    ['totale documento', replace(xml, /<ImportoTotaleDocumento>100\.00</, '<ImportoTotaleDocumento>102.00<')],
    ['negativa', replace(replace(replace(replace(xml, /<PrezzoUnitario>100\.00</, '<PrezzoUnitario>-100.00<'), /<PrezzoTotale>100\.00</, '<PrezzoTotale>-100.00<'), /<ImponibileImporto>100\.00</, '<ImponibileImporto>-100.00<'), /<ImportoTotaleDocumento>100\.00</, '<ImportoTotaleDocumento>-100.00<')],
  ];
  for (const [label, x] of cases) {
    const out = righeFromXml(parse(x));
    assert.equal(out.ok, false, label);
  }
});

test('mixed or partial VALUTA data is not representable', () => {
  const data: FatturaXMLData = { ...base, righe: [{ descrizione: 'A', quantita: 1, prezzoUnitario: 100 }, { descrizione: 'B', quantita: 1, prezzoUnitario: 50 }], valuta: 'GBP', tassoCambio: 0.84, dataCambio: '2026-03-09' };
  const xml = generateFatturaXML(data);
  const senzaSeconda = xml.replace(/(<\/NumeroLinea>[\s\S]*?<NumeroLinea>2<\/NumeroLinea>[\s\S]*?)<AltriDatiGestionali>[\s\S]*?<\/AltriDatiGestionali>/, '$1');
  assert.notEqual(senzaSeconda, xml);
  assert.equal(righeFromXml(parse(senzaSeconda)).ok, false);
});

test('a RiferimentoData with a timezone suffix keeps the valid date part', () => {
  const data: FatturaXMLData = { ...base, righe: [{ descrizione: 'W', quantita: 1, prezzoUnitario: 100 }], valuta: 'GBP', tassoCambio: 0.84, dataCambio: '2026-03-09' };
  const xml = generateFatturaXML(data).replace('<RiferimentoData>2026-03-09</RiferimentoData>', '<RiferimentoData>2026-03-09Z</RiferimentoData>');
  const out = righeFromXml(parse(xml));
  assert.equal(out.ok, true);
  if (out.ok) assert.equal(out.dataCambio, '2026-03-09');
});

test('a garbage RiferimentoData is dropped, import still succeeds without dataCambio', () => {
  const data: FatturaXMLData = { ...base, righe: [{ descrizione: 'W', quantita: 1, prezzoUnitario: 100 }], valuta: 'GBP', tassoCambio: 0.84, dataCambio: '2026-03-09' };
  const xml = generateFatturaXML(data).replace('<RiferimentoData>2026-03-09</RiferimentoData>', '<RiferimentoData>non-una-data</RiferimentoData>');
  const out = righeFromXml(parse(xml));
  assert.equal(out.ok, true);
  if (out.ok) assert.equal(out.dataCambio, undefined);
});

test('F1: rounded PrezzoUnitario is reconstructed from PrezzoTotale so the round trip preserves the original amounts', () => {
  const data: FatturaXMLData = { ...base, righe: [{ descrizione: 'Consulenza', quantita: 100, prezzoUnitario: 1.234 }] };
  const xml1 = generateFatturaXML(data);
  assert.match(xml1, /<PrezzoUnitario>1\.23<\/PrezzoUnitario>/);
  assert.match(xml1, /<PrezzoTotale>123\.40<\/PrezzoTotale>/);
  const out = righeFromXml(parse(xml1));
  assert.equal(out.ok, true);
  if (!out.ok) return;
  assert.equal(out.righe[0]!.prezzoUnitario, 1.234);
  const xml2 = generateFatturaXML({ ...base, righe: out.righe });
  assert.match(xml2, /<PrezzoTotale>123\.40<\/PrezzoTotale>/);
  assert.match(xml2, /<ImponibileImporto>123\.40</);
});

test('F1: reconstructed prices whose sum drifts from the declared imponibile are not representable', () => {
  const righe = Array.from({ length: 100 }, (_, i) => ({ descrizione: `Riga ${i + 1}`, quantita: 0.33, prezzoUnitario: 1.01 }));
  const xml = generateFatturaXML({ ...base, righe });
  assert.match(xml, /<ImponibileImporto>33\.33</);
  const out = righeFromXml(parse(xml));
  assert.equal(out.ok, false);
});

test('F2: a zero exchange rate in Causale is not representable', () => {
  const data: FatturaXMLData = { ...base, righe: [{ descrizione: 'Workshop', quantita: 1, prezzoUnitario: 100 }], valuta: 'GBP', tassoCambio: 0.84, dataCambio: '2026-03-09' };
  const xml = generateFatturaXML(data).replace('1 EUR = 0.84 GBP', '1 EUR = 0 GBP');
  const out = righeFromXml(parse(xml));
  assert.equal(out.ok, false);
});

test('F2: an exchange rate inconsistent with the amounts is not representable', () => {
  const data: FatturaXMLData = { ...base, righe: [{ descrizione: 'Workshop', quantita: 1, prezzoUnitario: 100 }], valuta: 'GBP', tassoCambio: 0.84, dataCambio: '2026-03-09' };
  const xml = generateFatturaXML(data).replace('1 EUR = 0.84 GBP', '1 EUR = 2 GBP');
  const out = righeFromXml(parse(xml));
  assert.equal(out.ok, false);
});

test('divergent RiferimentoData across VALUTA lines is not representable', () => {
  const data: FatturaXMLData = { ...base, righe: [{ descrizione: 'A', quantita: 1, prezzoUnitario: 100 }, { descrizione: 'B', quantita: 1, prezzoUnitario: 50 }], valuta: 'GBP', tassoCambio: 0.84, dataCambio: '2026-03-09' };
  const xml = generateFatturaXML(data);
  let count = 0;
  const changed = xml.replace(/<RiferimentoData>2026-03-09<\/RiferimentoData>/g, () => (++count === 2 ? '<RiferimentoData>2026-03-10</RiferimentoData>' : '<RiferimentoData>2026-03-09</RiferimentoData>'));
  assert.equal(count, 2);
  const out = righeFromXml(parse(changed));
  assert.equal(out.ok, false);
});
